services:
  svelte:
    build: ./svelte
    ports:
      - "4173:4173"
    command: npm run preview -- --host
    restart: always
    depends_on:
      - nodegql
    networks:
      - app-network

  nodegql:
    build: ./nodegql
    ports:
      - "9000:9000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=legalmatch
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    volumes:
      - data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: legalmatch
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  data:

networks:
  app-network:
    driver: bridge
